#!/usr/bin/env python3
"""Generate the public support site and the exact same offline documents for iOS."""
from pathlib import Path
import html, json, shutil, zipfile
ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / 'Web'
EMAIL = 'alperrbicer@gmail.com'
DATE = '2026-10-04'
APPLE_EULA = 'https://www.apple.com/legal/internet-services/itunes/dev/stdeula/'
COPY = {
 'tr': {
  'nav': ['Ana sayfa', 'Gizlilik', 'Kullanım koşulları', 'Yardım'],
  'tagline': 'Telefonundan, aracına.', 'intro': 'Kaynaklarını bir araya getir. Uyumlu ekranlarda görüntünün ve sesin keyfini çıkar.',
  'home': [('Kendi kaynakların', 'M3U listelerini, doğrudan yayın bağlantılarını ve Xtream Codes sunucularını tek kitaplıkta tut. Mirivo kanal, yayın paketi veya IPTV hesabı sağlamaz.'),
           ('Her zaman reklamsız', 'Mirivo reklam, reklam SDK’sı veya reklam takibi içermez. Ücretsiz sürüm ve Pro reklamsızdır.'),
           ('Cihazında kalır', 'Kaynak bilgilerin cihazında, ses ve görüntü geçici bellekte işlenir. Tanılama raporunu yalnızca sen paylaşırsın.'),
           ('Mirivo Pro', 'Sınırsız kaynak ve yayın, büyük kontrollerle araç modu, desteklenen cihaz ve dillerde canlı altyazı. Haftalık, yıllık veya tek ödemelik ömür boyu planı uygulamadan seçebilirsin.')],
  'privacyTitle': 'Gizlilik Politikası',
  'privacyIntro': 'Mirivo, Alper Biçer tarafından sunulur. Bu politika iOS uygulamasındaki veri işlemlerini ve bu destek sitesini açıklar.',
  'privacy': [
   ('Ekran ve uygulama sesi', 'Ekran paylaşımı iOS’un sistem onayıyla başlar. Görüntü ve uygulama sesi cihaz üzerinde işlenir ve seçilen uyumlu ekrana aktarılır. Mirivo bunları geliştiricinin sunucusuna yüklemez; video veya ses kaydı oluşturmaz. Aktarım parçaları sınırlı geçici bellekte tutulur ve oturum sona erdiğinde temizlenir. Mikrofon kaydı yapılmaz. Paylaşım sırasında ekranda görünen kişisel bilgiler ve bildirimler de görüntüye dahil olabilir; iOS yayın kontrolünden istediğin zaman durdurabilirsin.'),
   ('Yerel bağlantı', 'Ekran yayını için oturuma özel, tahmin edilmesi güç erişim adresi kullanılır. Yerel aktarım HTTP üzerinden yapılabilir; bu bir uçtan uca şifreleme vaadi değildir. Erişim adresi günlüklerde veya paylaşılabilir tanılama raporunda yer almaz. Yayın durdurulduğunda erişim kapatılır.'),
   ('Kaynaklar ve hesap bilgileri', 'Eklediğin kaynak adları ve türleri uygulamanın yerel alanında; yayın adresleri, kullanıcı adı ve parolalar iOS Keychain’de bu cihaza bağlı olarak saklanır. Kanal listeleri açıldığında belleğe alınır. Mirivo bu verileri kendi sunucusuna kopyalamaz veya iCloud eşitlemesi yapmaz. Seçtiğin kaynak sunucusu bağlantı kurulduğunda IP adresini, istenen içeriği ve gerektiğinde giriş bilgilerini alır; o sağlayıcının koşulları geçerlidir. HTTP kullanan bir kaynak aktarımı şifrelemez; mümkünse HTTPS kullan.'),
   ('Canlı altyazılar', 'Bu özelliği açtığında desteklenen cihaz ve dillerde Apple’ın cihaz içi konuşma modelleri kullanılır. İlk hazırlıkta Apple’dan dil dosyası indirilebilir. Ses ve üretilen metin Mirivo tarafından bir sunucuya gönderilmez; kalıcı transkript oluşturulmaz. Altyazı video karesine eklenir ve geçici metin durdurulduğunda temizlenir. Tanıma sonucu hatalı olabilir.'),
   ('Tercihler ve tanılama', 'Dil, kalite, ses ve altyazı tercihleri cihazda saklanır. Son 10 oturuma ait teknik kayıtlar toplam en fazla 5 MiB olacak şekilde tutulur. Kayıtlar durum, hata kodu, süre, kare/ses sayaçları ve bağlantı türü gibi teknik alanlarla sınırlıdır. Ekran içeriği, ses, altyazı, kaynak adresi, erişim anahtarı, IPTV hesabı, parola ve cihaz adı rapora eklenmez. Rapor otomatik gönderilmez; sistem paylaşım ekranında alıcıyı sen seçersin. Mirivo reklam SDK’sı kullanmaz; satın alma yönetimi RevenueCat ile yürütülebilir.'),
   ('Satın alımlar', 'Ödeme ve abonelik işlemleri Apple App Store tarafından yürütülür. Kart bilgilerini Mirivo almaz. Uygulama erişim hakkını cihazda doğrulanmış StoreKit işlemleriyle belirler. RevenueCat yapılandırıldığında rastgele uygulama kullanıcı kimliği, satın alma ve abonelik kayıtları ile teknik bağlantı bilgilerini satın alma yönetimi için işler. Kaynaklar, parolalar, ekran, ses ve altyazılar bu servise gönderilmez.'),
   ('Destek ve bu site', 'Destek için e-posta gönderirsen adresin, mesajın ve kendi isteğinle eklediğin dosyalar yanıt vermek için kullanılır. Ekran kaydı, yayın parolası veya kişisel içerik göndermen gerekmez. Mesajlar destek talebi ve uygulanabilir yükümlülükler için gerekli süre boyunca tutulur. Bu statik sitede reklam, analiz çerezi, form veya izleme betiği yoktur. Site Netlify üzerinde yayımlandığında Netlify, isteği sunmak ve altyapıyı korumak için IP adresi gibi teknik bağlantı verilerini kendi gizlilik politikasına göre işleyebilir.'),
   ('Silme ve tercihlerin', 'Ayarlar’dan kayıtları temizleyebilir ve tüm kaynakları, kayıtlı giriş bilgileriyle birlikte silebilirsin. Bir kaynağı tek başına da silebilirsin. Kaynakları silmek için uygulama kaldırılmadan önce bu kontrolleri kullan; Keychain verileri uygulamanın kaldırılmasından sonra sistemde kalabilir. Yerel veriler otomatik olarak Mirivo hesabına yedeklenmez. Gönderdiğin destek verileri veya uygulanabilir erişim, düzeltme ve silme hakların için aşağıdaki adrese yazabilirsin.'),
   ('İletişim ve güncellemeler', f'Veri sorumlusu/yayıncı: Alper Biçer. İletişim: {EMAIL}. Uygulamanın veri işleme biçimi değişirse bu politika güncellenir; güncel tarih bu sayfada gösterilir.')],
  'termsTitle': 'Kullanım Koşulları (EULA)',
  'termsIntro': 'Mirivo’nun uygulama lisansı Apple’ın Standart Son Kullanıcı Lisans Sözleşmesi’ne (EULA) tabidir. Aşağıdaki ürün koşulları kullanım, içerik ve ödeme işleyişini açıklar; zorunlu tüketici haklarını sınırlandırmaz.',
  'terms': [
   ('Uygulama ve içerik', 'Mirivo, kendi kaynaklarını oynatman ve izin verilen ekran içeriğini uyumlu ekranlara aktarman için araçlar sunar. Kanal listesi, IPTV aboneliği, YouTube içeriği veya başka bir üçüncü tarafın aboneliği satın alıma dahil değildir. Kullandığın içerik için gerekli erişim ve kullanım haklarına sahip olmalısın; içerik sağlayıcısının koşulları ayrıca geçerlidir.'),
   ('Cihaz ve uyumluluk', 'iPhone uygulaması iOS 18 ve sonrasını hedefler. Resmî CarPlay video yolu iOS 26.4 ve destekleyen araç/bağlantı gerektirir. Canlı altyazı iOS 26 ve cihazda desteklenen bir dil gerektirir. Araç, adaptör, iOS sürümü, kaynak uygulama ve içerik koruması sonucu etkiler. Bir araçta başka bir uygulamanın çalışması Mirivo uyumluluğunu garanti etmez. DRM veya kaynak uygulama kısıtlamalarını kaldırma hizmeti sunulmaz. Araçta video yalnızca sistemin izin verdiği koşullarda ve park hâlinde kullanılmalıdır.'),
   ('Ücretsiz sürüm ve Pro', 'Ücretsiz sürümde günlük iki saat izleme, bir kayıtlı kaynak ve yayın başına on dakika sunulur. Pro bu sınırları kaldırır; araç modu ve desteklenen canlı altyazıları açar. Mirivo’nun hiçbir sürümünde reklam yoktur. Uygulamadaki satın alma ekranı özellikleri, planı ve fiyatı açıkça gösterir; ücretli erişim ancak sen Apple satın alma onayını verdikten sonra başlar. Pro, desteklenmeyen cihazlara veya korumalı içeriğe erişim garantisi vermez.'),
   ('Abonelik ve tek seferlik satın alma', 'Planlar haftalık, yıllık ve tek seferlik ömür boyu Pro erişimidir. Satışa açılan planlar ve yerelleştirilmiş fiyatlar App Store’dan alınır; bu sayfa bir fiyat veya kampanya teklifi değildir. Abonelikler iptal edilmedikçe seçilen dönem boyunca otomatik yenilenir ve ödeme Apple hesabından alınır. İptal ve yönetim App Store hesap ayarlarındadır; uygulamayı silmek aboneliği iptal etmez. Ömür boyu plan tek ödeme ile satın alınan Mirivo Pro özelliklerine kalıcı erişim lisansıdır; üçüncü taraf servislerin veya tüm gelecek işletim sistemi ve donanımların sonsuz desteği anlamına gelmez.'),
   ('Geri yükleme ve iade', 'Aynı Apple hesabındaki uygun satın alımlar “Satın alımları geri yükle” ile geri alınabilir. İade talepleri Apple’ın iade süreci üzerinden değerlendirilir. İptal, iade, yenileme ve erişim haklarında Apple’ın kuralları ve yürürlükteki zorunlu tüketici hakları geçerlidir.'),
   ('Kullanım ve sorumluluk', 'Uygulamayı hukuka, içerik lisanslarına ve cihazın kullanım kurallarına uygun kullan. Paylaşımı başlatmadan önce ekranda gösterilecek içeriği kontrol et. Kaynak sunucularının sürekliliği, ağ kalitesi ve üçüncü taraf içerik değişiklikleri Mirivo’nun kontrolünde değildir. Uygulama arızaları için destek alabilirsin. Apple EULA’sındaki hükümler, uygulanabilir zorunlu hukuk ve tüketici hakları saklı kalmak üzere geçerlidir.'),
   ('Yayıncı ve iletişim', f'Mirivo’nun yayıncısı Alper Biçer’dir. Destek ve koşullarla ilgili sorular: {EMAIL}. Ürün koşullarındaki değişiklikler bu sayfada tarihleriyle yayımlanır; satın alma anında açıklanmış haklar zorunlu hukuka aykırı biçimde geriye dönük daraltılmaz.')],
  'supportTitle': 'Yardım ve SSS', 'supportIntro': 'Kısa yanıtlar, bağlantı adımları ve doğrudan destek.',
  'support': [
   ('Uygulama dilini nasıl değiştiririm?', 'Ayarlar → Dil bölümünde bir dil seç veya Sistemi izle seçeneğini kullan. Dilin kendi adı, çevrilmiş adı veya dil koduyla arama yapabilirsin. Arayüz 22 dilde sunulur. Gizlilik, kullanım koşulları ve yardım sayfalarında Türkçe veya İngilizce seçebilirsin.'),
   ('CarPlay’de nasıl ses dinlerim?', 'Önce iPhone’da Kaynaklar bölümüne kendi yayın bağlantını veya oynatma listeni ekle. CarPlay’de Mirivo → Kaynaklar yolundan bir yayın seç. Şu An Çalıyor ekranında oynatabilir, duraklatabilir ve araç kontrollerini kullanabilirsin. Audio sürümünde araçta ses çalar; ekran paylaşımı Video desteği gerektirir.'),
   ('Ekran paylaşımını nasıl başlatırım?', 'Bu özellik CarPlay Video yetkili Mirivo sürümü ve video destekli araç bağlantısı gerektirir. Uyumlu bağlantıda araç ekranında Mirivo’yu aç, telefonda Yansıt sekmesindeki sistem yayın düğmesine dokun ve Mirivo yayınını başlat. Ardından izlemek istediğin uygulamaya geç. Durdurmak için Mirivo’daki durdurma düğmesini veya iOS yayın kontrolünü kullan.'),
   ('CarPlay’de simge veya görüntü neden görünmüyor?', 'Araç, bağlantı, uygulamanın imzalandığı CarPlay yetkileri ve iOS’un video desteği birlikte belirleyicidir. Araç park hâlindeyken önce doğrudan kabloyla dene. Kablosuz adaptör kullanıyorsan aynı akışı ayrı test et. Ekran yakalamanın başlaması tek başına araçta video çıkışı olduğu anlamına gelmez. Ayarlar’dan tanılama raporu oluşturup destekle paylaşabilirsin.'),
   ('YouTube veya başka bir uygulama siyah görünüyor.', 'Bazı uygulamalar ve korumalı içerikler ekran yakalamaya izin vermez. Mirivo DRM korumasını kaldırmaz. Erişim izni olan başka bir içerikle dene; kaynak uygulamanın koşulları ve sistem desteği geçerlidir.'),
   ('Ses gecikiyor veya iki kez duyuluyor.', 'Ayarlar → Ses bölümünde “Görüntüyle birlikte” sesi yayınla taşır; “Kaynak uygulamadan” kaynak uygulamanın kendi ses rotasını korur. Değişiklikten sonra ekran paylaşımını yeniden başlat. Araç ve kaynak uygulamaya göre uygun seçenek değişebilir.'),
   ('IPTV ve M3U kaynağı nasıl eklenir?', 'Kaynaklar → + yolunu aç. M3U oynatma listesi, doğrudan yayın veya Xtream Codes türünü seç. Bir ad ve sağlayıcının verdiği adresi gir; Xtream için kullanıcı adı ve parola gerekir. Mirivo içerik veya hesap sağlamaz. HTTPS adresi tercih et; şifrelenmemiş HTTP listeleri sistem tarafından engellenebilir.'),
   ('Araç modu ve altyazılar nerede?', 'Bir kaynağı oynatırken Araç modu büyük kontrollerle oynatıcıyı açar; telefonu döndürdüğünde yatay alana uyarlanır. Kaynağın sunduğu altyazılar oynatıcının altyazı menüsündedir. Ekran paylaşımına konuşmadan altyazı eklemek için Ayarlar → Canlı altyazılar yolundan desteklenen dili hazırla. İlk indirme internet ister; konuşma tanıma cihazda yapılır.'),
   ('Pro ve reklamlar nasıl çalışıyor?', 'Mirivo her sürümde reklamsızdır. Ücretsiz sürümde günde 2 saat izleme, bir kayıtlı kaynak ve yayın başına 10 dakika sunulur. Pro bu sınırları kaldırır ve araç modu ile desteklenen canlı altyazıları açar. Fiyat ve yenileme koşulları satın alma ekranında gösterilir; sen onaylamadan ödeme alınmaz.'),
   ('Verilerimi veya kayıtlarımı nasıl silerim?', 'Ayarlar’dan Kayıtları temizle ile teknik günlükleri, Tüm kaynakları sil ile kaynakları ve Keychain’deki giriş bilgilerini kaldır. Kaldırmadan önce bu işlemi yapman önerilir. Tanılama raporunu paylaştıysan gönderdiğin kopyayı alıcıdan ayrıca silmesini isteyebilirsin.'),
   ('Destek için ne göndermeliyim?', f'{EMAIL} adresine iOS ve Mirivo sürümünü, araç modelini, kablolu/kablosuz bağlantı bilgisini ve sorunun adımlarını yaz. İstersen Ayarlar’dan oluşturduğun tanılama raporunu ekle. IPTV parolanı, yayın adresini veya kişisel ekran içeriğini göndermen gerekmez.')]
 },
 'en': {
  'nav': ['Home', 'Privacy', 'Terms', 'Help'],
  'tagline': 'From your phone. To your car.', 'intro': 'Bring your sources together. Enjoy picture and sound on compatible displays.',
  'home': [('Your own sources', 'Keep M3U playlists, direct streams and Xtream Codes servers in one library. Mirivo does not provide channels, content packages or IPTV accounts.'),
           ('Always ad-free', 'Mirivo contains no ads, advertising SDKs or ad tracking. The free tier and Pro are both ad-free.'),
           ('On your device', 'Source details stay on your device. Audio and video are processed in temporary memory. You choose whether to share a diagnostic report.'),
           ('Mirivo Pro', 'Unlimited sources and broadcasts, vehicle mode with larger controls, and live captions on supported devices and languages. Pro is not on sale yet.')],
  'privacyTitle': 'Privacy Policy', 'privacyIntro': 'Mirivo is provided by Alper Biçer. This policy describes data handling in the iOS app and on this support website.',
  'privacy': [
   ('Screen and app audio', 'Screen sharing begins with the iOS system confirmation. Video and app audio are processed on your device and transmitted to the selected compatible display. Mirivo does not upload them to a developer server or create an audio or video recording. Media fragments are held in bounded temporary memory and removed when the session ends. Mirivo does not record the microphone. Personal information and notifications visible on the screen may be included in the broadcast. You can stop it at any time using the iOS broadcast control.'),
   ('Local connection', 'Screen broadcasts use a hard-to-guess, per-session access address. Local transmission may use HTTP; this is not a promise of end-to-end encryption. The access address is excluded from logs and exported diagnostic reports. Access is revoked when sharing stops.'),
   ('Sources and credentials', 'Source names and types are stored in the app’s local storage. Stream URLs, usernames and passwords are stored in iOS Keychain with device-only accessibility. Channel lists are loaded into memory. Mirivo does not copy this information to a developer server or provide iCloud synchronization. Your chosen content server receives your IP address, requested content and any necessary credentials when you connect; its own policies apply. HTTP sources do not encrypt transport. Prefer HTTPS when available.'),
   ('Live captions', 'When enabled on a supported device and language, live captions use Apple’s on-device speech models. Initial setup may download a language model from Apple. Mirivo does not send speech or generated text to a server or create a persistent transcript. Captions are composited into the video and temporary text is cleared on stop. Recognition may be inaccurate.'),
   ('Preferences and diagnostics', 'Language, quality, audio and caption preferences stay on the device. Technical logs retain up to 10 recent sessions within a total 5 MiB budget. They contain structured states, error codes, timing, media counters and connection types. Screen content, audio, captions, source URLs, tokens, IPTV accounts, passwords and device names are excluded. Reports are not sent automatically; you select the recipient in the system share sheet. Mirivo uses no advertising SDK. When RevenueCat is configured, its purchase SDK processes a random app user identifier, purchase and subscription records, and technical connection information to verify and manage Pro purchases. Source credentials, screen content, audio and captions are not sent to RevenueCat.'),
   ('Purchases', 'Apple App Store handles payment and subscriptions. Mirivo does not receive payment card details. Access is determined from locally verified StoreKit transactions. '),
   ('Support and this website', 'If you email support, your email address, message and any attachments you choose to send are used to respond. You do not need to send screen recordings, stream passwords or personal content. Messages are retained as needed to resolve the request and meet applicable obligations. This static website has no ads, analytics cookies, forms or tracking scripts. When hosted on Netlify, Netlify may process technical connection details, including IP addresses, to serve and secure the website under its own privacy policy.'),
   ('Deletion and choices', 'Settings lets you clear diagnostics and delete all sources together with saved credentials. Individual sources can also be removed. Use these controls before uninstalling the app; iOS Keychain entries can survive app removal. Mirivo does not automatically back up local data to a Mirivo account. Contact us below regarding support information you sent or applicable access, correction and deletion rights.'),
   ('Contact and updates', f'Publisher and data controller: Alper Biçer. Contact: {EMAIL}. We update this policy when data handling changes; the current date appears on this page.')],
  'termsTitle': 'Terms of Use (EULA)', 'termsIntro': 'The Mirivo application license is governed by Apple’s Standard End User License Agreement. The product terms below explain use, content and payments without limiting mandatory consumer rights.',
  'terms': [
   ('App and content', 'Mirivo provides tools for playing your own sources and sharing permitted screen content with compatible displays. Channel lists, IPTV subscriptions, YouTube content and other third-party subscriptions are not included in any purchase. You must have the necessary access and usage rights for your content. Content providers’ terms also apply.'),
   ('Devices and compatibility', 'The iPhone app targets iOS 18 or later. The official CarPlay video route requires iOS 26.4 and a supporting vehicle and connection. Live captions require iOS 26 and a supported on-device language. Results depend on your vehicle, adapter, iOS version, source app and content protection. Another app working in a vehicle does not guarantee Mirivo compatibility. Mirivo does not remove DRM or source-app restrictions. In-car video must only be used while parked and when permitted by the system.'),
   ('Free version and Pro', 'The free tier includes two hours of daily viewing, one saved source and ten minutes per broadcast. Pro removes these limits and adds vehicle mode and supported live captions. Every Mirivo version is ad-free. The purchase screen shows available plans, localized prices and renewal terms. Paid access begins only after you confirm an Apple purchase. Pro does not guarantee access on unsupported devices or to protected content.'),
   ('Subscriptions and one-time purchases', 'Plans include weekly, yearly and one-time lifetime Pro access. Available plans and localized prices come from the App Store; this page is not a price or promotional offer. Subscriptions automatically renew for the selected period unless cancelled, with payment charged to your Apple account. Manage or cancel in App Store account settings; deleting the app does not cancel a subscription. Lifetime is a permanent license to the purchased Mirivo Pro features for one payment. It does not mean perpetual availability of third-party services or support for every future operating system and device.'),
   ('Restore and refunds', 'Eligible purchases on the same Apple account can be recovered with Restore Purchases. Refund requests are handled through Apple’s refund process. Apple’s rules and mandatory consumer rights apply to cancellation, refunds, renewal and access.'),
   ('Use and responsibility', 'Use the app in accordance with law, content licenses and device rules. Check what is visible before starting screen sharing. Source availability, network quality and third-party content changes are outside Mirivo’s control. Contact support for app issues. The Apple EULA applies subject to applicable mandatory law and consumer rights.'),
   ('Publisher and contact', f'Mirivo is published by Alper Biçer. Support and terms enquiries: {EMAIL}. Changes to these product terms are published with their date. Previously disclosed purchase rights are not retroactively reduced contrary to mandatory law.')],
  'supportTitle': 'Help & FAQ', 'supportIntro': 'Quick answers, connection steps and direct support.',
  'support': [
   ('How do I change the app language?', 'Open Settings → Language and choose a language or Follow system. Search by a native or translated language name, or by language code. The interface supports 22 languages. Privacy, terms and help pages let you choose Turkish or English.'),
   ('How do I listen through CarPlay?', 'Add your own stream or playlist in Sources on your iPhone. In CarPlay, open Mirivo → Sources and choose a stream. Use Now Playing or your car’s controls to play and pause. The Audio version plays sound in your car; screen sharing requires Video support.'),
   ('How do I start screen sharing?', 'This feature requires a CarPlay Video-enabled version of Mirivo and a vehicle connection that supports video. With a compatible connection, open Mirivo on the car display, then tap the system broadcast control in the phone’s Mirror tab and start the Mirivo broadcast. Switch to your source app. Stop with the Mirivo stop button or the iOS broadcast control.'),
   ('Why is the CarPlay icon or video missing?', 'The vehicle, connection, signed CarPlay entitlements and iOS video support all matter. While parked, try a direct cable first. Test a wireless adapter separately. Starting screen capture alone does not confirm video output in the car. Export a diagnostic report from Settings to share with support.'),
   ('Why does YouTube or another app show a black screen?', 'Some apps and protected content do not permit screen capture. Mirivo does not bypass DRM. Try other content you may access; source-app terms and system support apply.'),
   ('Audio is delayed or plays twice.', 'In Settings → Audio, With video carries audio in the broadcast; From source app preserves the source app’s own audio route. Restart screen sharing after changing the setting. The suitable option can vary by vehicle and source app.'),
   ('How do I add IPTV or an M3U source?', 'Open Sources → +. Select M3U playlist, direct stream or Xtream Codes. Enter a name and the provider’s address; Xtream also requires a username and password. Mirivo does not provide content or accounts. Prefer HTTPS; the system may block unencrypted HTTP playlists.'),
   ('Where are vehicle mode and captions?', 'While playing a source, Vehicle mode opens a player with large controls and adapts to landscape when you rotate the phone. Source-provided subtitles are available in the player’s subtitle menu. To add speech captions to a screen broadcast, prepare a supported language in Settings → Live captions. The first download needs internet; speech recognition runs on the device.'),
   ('How do Pro and ads work?', 'Every Mirivo version is ad-free. The free tier includes two hours of daily viewing, one saved source and ten minutes per broadcast. Pro removes these limits and adds vehicle mode and supported live captions. Real prices and terms appear on the purchase screen. Payment requires your confirmation.'),
   ('How do I remove my data?', 'In Settings, Clear logs removes technical diagnostics. Delete all sources removes sources and Keychain credentials. Do this before uninstalling. If you shared a report, ask its recipient separately to delete their copy.'),
   ('What should I send to support?', f'Email {EMAIL} with the iOS and Mirivo versions, car model, wired or wireless connection and steps that reproduce the issue. You may attach the diagnostic report exported from Settings. Do not send IPTV passwords, stream URLs or personal screen content.')]
 }
}

def esc(text): return html.escape(text, quote=True)
def layout(lang, page, title, intro, content):
 c=COPY[lang]; other='en' if lang=='tr' else 'tr'
 nav=''.join(f'<a href="{name}.html"'+(' aria-current="page"' if name==page else '')+f'>{esc(label)}</a>' for name,label in zip(['index','privacy','terms','support'],c['nav']))
 return f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="description" content="{esc(intro)}"><title>{esc(title)} · Mirivo</title><link rel="icon" href="../assets/mark.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/style.css"></head>
<body><a class="skip" href="#content">{'İçeriğe geç' if lang=='tr' else 'Skip to content'}</a><header><a class="brand" href="index.html"><img src="../assets/mark.svg" width="38" height="38" alt=""><span>Mirivo</span></a><a class="language" href="../{other}/{page}.html" lang="{other}">{'English' if lang=='tr' else 'Türkçe'}</a></header><nav aria-label="{'Ana menü' if lang=='tr' else 'Main navigation'}">{nav}</nav><main id="content"><div class="eyebrow">MIRIVO · {'DESTEK' if lang=='tr' else 'SUPPORT'}</div><h1>{esc(title)}</h1><p class="lead">{esc(intro)}</p><p class="date">{'Güncelleme' if lang=='tr' else 'Updated'}: <time datetime="{DATE}">{'4 Ekim 2026' if lang=='tr' else 'October 4, 2026'}</time></p>{content}</main><footer><div>© 2026 Alper Biçer · Mirivo</div><a href="mailto:{EMAIL}">{EMAIL}</a><p>{'Her sürümde reklamsız.' if lang=='tr' else 'Ad-free in every version.'}</p></footer></body></html>'''

def main():
 for lang,c in COPY.items():
  directory=WEB/lang;directory.mkdir(parents=True,exist_ok=True)
  cards='<div class="cards">'+''.join(f'<section><h2>{esc(a)}</h2><p>{esc(b)}</p></section>' for a,b in c['home'])+'</div>'
  (directory/'index.html').write_text(layout(lang,'index',c['tagline'],c['intro'],cards))
  for page in ['privacy','terms','support']:
   body=''.join(f'<section><h2>{esc(a)}</h2><p>{esc(b)}</p></section>' for a,b in c[page])
   if page=='terms': body=f'<a class="action" href="{APPLE_EULA}">{"Apple Standart EULA" if lang=="tr" else "Apple Standard EULA"} ↗</a>'+body+f'<p><a href="https://apps.apple.com/account/subscriptions">{"Abonelikleri yönet" if lang=="tr" else "Manage subscriptions"}</a> · <a href="https://reportaproblem.apple.com/">{"Apple iade desteği" if lang=="tr" else "Apple refund support"}</a></p>'
   if page=='privacy': body+='<p><a href="https://www.netlify.com/privacy/">Netlify Privacy Policy ↗</a></p>'
   if page=='support': body=f'<a class="action" href="mailto:{EMAIL}?subject=Mirivo">{"Destek için yaz" if lang=="tr" else "Email support"} ↗</a>'+body
   (directory/f'{page}.html').write_text(layout(lang,page,c[page+'Title'],c[page+'Intro'],body))
 (WEB/'index.html').write_text('''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Mirivo</title><link rel="stylesheet" href="assets/style.css"></head><body><main><img src="assets/mark.svg" width="76" height="76" alt="Mirivo"><h1>Mirivo</h1><p class="lead">Telefonundan, aracına.<br>From your phone. To your car.</p><a class="action" href="tr/index.html" lang="tr">Türkçe</a> <a class="action" href="en/index.html" lang="en">English</a></main></body></html>''')
 for alias,page in [('privacy','privacy'),('terms','terms'),('support','support')]:
  # Stable root URLs work without Netlify redirects or a chosen domain.
  text=(WEB/'tr'/f'{page}.html').read_text().replace('../assets/','assets/').replace('../en/','en/').replace('href="index.html"','href="tr/index.html"')
  for target in ['privacy','terms','support']:text=text.replace(f'href="{target}.html"',f'href="tr/{target}.html"')
  (WEB/f'{alias}.html').write_text(text)
 shutil.copyfile(ROOT/'Design/mirror-mark.svg', WEB/'assets/mark.svg')
 bundled=ROOT/'Resources/Legal'
 bundled.mkdir(parents=True,exist_ok=True)
 for directory in ['tr','en','assets']:
  shutil.copytree(WEB/directory,bundled/directory,dirs_exist_ok=True)
 output=ROOT/'Release/mirivo-netlify.zip';output.parent.mkdir(exist_ok=True)
 with zipfile.ZipFile(output,'w',zipfile.ZIP_DEFLATED) as archive:
  for path in sorted(WEB.rglob('*')):
   if path.is_file():archive.write(path,path.relative_to(WEB))
 print(output)
if __name__=='__main__':main()
